services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ../src:/var/www
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

  nginx:
    image: nginx:1.21.1-alpine
    restart: unless-stopped
    ports: 
      - "8000:80"
    volumes: 
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app